"""Generates Colab notebooks (TPU + GPU) for a given training run."""
from __future__ import annotations

import json
import uuid
from pathlib import Path
from typing import Any

import nbformat as nbf
from jinja2 import Environment, FileSystemLoader, select_autoescape

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"
RUNS_DIR = Path(__file__).parent.parent / "generated_notebooks"
RUNS_DIR.mkdir(exist_ok=True)

env = Environment(
    loader=FileSystemLoader(str(TEMPLATES_DIR)),
    autoescape=select_autoescape(["html", "xml"]),
    keep_trailing_newline=True,
)


def _md_cell(source: str) -> dict:
    return nbf.v4.new_markdown_cell(source)


def _code_cell(source: str) -> dict:
    return nbf.v4.new_code_cell(source)


def render_training_notebook(
    *,
    run_id: uuid.UUID,
    base_model: str,
    hardware: str,
    method: str,
    dataset_uri: str,
    config: dict[str, Any],
) -> Path:
    """Build a Colab-ready .ipynb for the given training run config."""
    nb = nbf.v4.new_notebook()
    cells: list[dict] = []

    title = f"# vForge — Fine-tune `{base_model}` on {hardware.upper()}"
    cells.append(
        _md_cell(
            f"{title}\n\n"
            f"- **Method:** {method.upper()}\n"
            f"- **Dataset:** `{dataset_uri}`\n"
            f"- **Run ID:** `{run_id}`\n\n"
            "Generated by vForge for the Google TPU Sprint Q1 2026."
        )
    )

    cells.append(_md_cell("## 1. Install dependencies"))
    if hardware == "tpu":
        cells.append(
            _code_cell(
                "!pip -q install -U jax[tpu] keras==3.6.0 keras-nlp==0.18.1 keras-hub "
                "datasets transformers tensorflow huggingface_hub\n"
                "import os; os.environ['KERAS_BACKEND'] = 'jax'"
            )
        )
    else:
        cells.append(
            _code_cell(
                "!pip -q install -U torch transformers peft trl datasets accelerate "
                "bitsandbytes huggingface_hub"
            )
        )

    cells.append(_md_cell("## 2. Load dataset"))
    cells.append(
        _code_cell(
            "from datasets import load_dataset\n"
            f"ds = load_dataset('json', data_files='{dataset_uri}', split='train')\n"
            "print(ds)\n"
            "print(ds[0])"
        )
    )

    cells.append(_md_cell("## 3. Run fine-tuning"))
    cfg_json = json.dumps(config, indent=2)
    if hardware == "tpu":
        cells.append(
            _code_cell(
                f"CONFIG = {cfg_json}\n"
                f"BASE_MODEL = '{base_model}'\n\n"
                "!python -m scripts.finetune_tpu \\\n"
                f"    --model {base_model} \\\n"
                f"    --data {dataset_uri} \\\n"
                "    --rank %d --epochs %d --batch-size %d --lr %s --max-seq-len %d --output ./out_tpu"
                % (
                    config.get("rank", 8),
                    config.get("epochs", 1),
                    config.get("batch_size", 4),
                    config.get("lr", "1e-4"),
                    config.get("max_seq_len", 1024),
                )
            )
        )
    else:
        cells.append(
            _code_cell(
                f"CONFIG = {cfg_json}\n"
                f"BASE_MODEL = '{base_model}'\n\n"
                "!python -m scripts.finetune_gpu \\\n"
                f"    --model {base_model} \\\n"
                f"    --data {dataset_uri} \\\n"
                "    --rank %d --epochs %d --batch-size %d --lr %s --max-seq-len %d --output ./out_gpu"
                % (
                    config.get("rank", 8),
                    config.get("epochs", 1),
                    config.get("batch_size", 4),
                    config.get("lr", "1e-4"),
                    config.get("max_seq_len", 1024),
                )
            )
        )

    cells.append(_md_cell("## 4. Benchmark inference with vLLM"))
    cells.append(
        _code_cell(
            "!pip -q install vllm\n"
            "!python -m scripts.benchmark_vllm \\\n"
            f"    --model ./out_{hardware} \\\n"
            f"    --hardware {hardware} \\\n"
            "    --prompts 256 --max-tokens 256"
        )
    )

    cells.append(_md_cell("## 5. Push results to HuggingFace (optional)"))
    cells.append(
        _code_cell(
            "from huggingface_hub import HfApi\n"
            "import os\n"
            "# api = HfApi(token=os.environ['HF_TOKEN'])\n"
            "# api.upload_folder(folder_path='./out_%s', repo_id='your-org/your-model')" % hardware
        )
    )

    nb["cells"] = cells
    out = RUNS_DIR / f"run_{run_id}_{hardware}.ipynb"
    out.write_text(nbf.writes(nb), encoding="utf-8")
    return out
